### ISSUE TITLE
value-files with multiple files: JSON string of array?

### ISSUE THREAD

**Issue by kierenj** [deliverybot/helm#19]
I'm trying to specify multiple value files. I've tried a JSON array as a string, as suggested:

```
          value-files: '[
            "api/config/env-base/values.yaml",
            "api/config/env-dev/values.yaml",
            ]'
```

However, the process fails with an error opening a file with the name of the entire JSON string.

Would it be possible to provide an example to demonstrate how this should work?

**Comment by colinjfw** [comment]
@kierenj ya it's a bit tricky to pass arguments with actions, I wish it would just allow full yaml syntax and pass that along somehow to the action.

The code that does this is here: https://github.com/deliverybot/helm/blob/master/index.js#L81-L97

I believe what's happening is you have a trailing slash in the array which is causing it to be invalid JSON, if it's invalid the action just tries to interpret it as a string. If you remove the trailing slash everything *should* work :)

**Comment by riker09** [comment]
This is what I'm doing:

```yaml
    - uses: deliverybot/helm@v1
      with:
        helm: helm3
        release: foobar
        namespace: default
        chart: path/to/chart
        dry-run: true
        value-files: '["values.yaml", "values.production.yaml"]'
```

You shouldn't indent the values. If you really want to (eg. for readability) I believe this is valid YAML:

```yaml
    - uses: deliverybot/helm@v1
      with:
        helm: helm3
        release: foobar
        namespace: default
        chart: path/to/chart
        dry-run: true
        value-files: >-
          [
            "values.yaml", 
            "values.production.yaml",
          ]
```

Here is helpful information on how to deal with strings that contain multiple new lines: https://yaml-multiline.info/

**Comment by colinjfw** [comment]
Thanks @riker09 - I think the trailing slash would still cause an error.

**Comment by riker09** [comment]
What trailing slash are we talking about? I can spot a trailing comma which *may* cause an error.

**Comment by colinjfw** [comment]
Ya my bad I actually meant comma

**Comment by riker09** [comment]
So in conclusion a perfectly valid configuration would look like this:

```yaml
    - uses: deliverybot/helm@v1
      with:
        helm: helm3
        release: foobar
        namespace: default
        chart: path/to/chart
        dry-run: true
        value-files: >-
          [
            "values.yaml", 
            "values.production.yaml"
          ]
```

> Notice the removed comma on the second to last line.
