### ISSUE TITLE
Howto reuse values?

### ISSUE THREAD

**Issue by riker09** [deliverybot/helm#24]
I want to establish the following workflow: In a microservice architectured application I have 20+ different apis, each is build as Docker image via GitHub Action and pushed into the GitHub Docker Registry. I want to utilize the [`registry_package` event ](https://help.github.com/en/actions/reference/events-that-trigger-workflows#registry-package-event-registry_package) and update my helm chart when a package (read: Docker image) is updated.

During development I was using this command:

```bash
helm upgrade release-name path/to/chart/ --reuse-values --set service-name.image.tag=1234abc
```

Before this step I built and published a Docker image with the tag `:1234abc`, of course. The tag name is the first seven chars of the GitHub SHA that triggered the build in the first place, in case you are wondering.

How can this be done with the `deliverybot/helm` GitHub Action? I'm not sure if this the way to go. I am thankful for any hints or other solutions.

**Comment by colinjfw** [comment]
I believe this should look something like the structure below. It does have two problems:
- I'm not sure how to get the short 7 char sha here.
- I don't think that reuse-values is a valid option but we could easily add that to the arguments.

```
# .github/workflows/deploy.yml
name: Deploy
on: ['registry_package']

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1

    - name: 'Update'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'nginx'
        namespace: 'default'
        chart: 'app'
        token: '${{ github.token }}'
        reuse-values: true # TODO: Need to add this as an option I believe.
        values: |
          service-name:
            image:
              tag: '${{ github.sha }}' # TODO: This isn't the short sha not sure how to get that.
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
```

**Comment by riker09** [comment]
This looks promising. Getting a short GITHUB_SHA could be done by a previous step.

```yaml
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1

    - name: 'Create short SHA'
      runs: |
        export SHORT_SHA=${GITHUB_SHA:0:7}

    - name: 'Update'
      # [...]
```

This is not tested, I hust assume that the exported value is available in subsequent steps. I *definitely* could make it work with a custom action.
